maven:
  path: 'maven'
  useCentral: true
  repositories:
    - id: 'spigot-repo'
      url: 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
  deleteOnStart: true
  artifacts:
    - 'org.spigotmc:spigot-api:1.21.4-R0.1-SNAPSHOT'
  dependencyScope: 'runtime'

jdkSources:
  translate: false
  path: 'jdk-sources'
  group: 'openjdk'
  name: 'jdk'
  version: '17'

output:
  path: 'generated'
  deleteOnStart: true

importExclusions:
  packages:
    - 'java.lang'
    - 'java.lang.annotation'
    - 'java.awt'
    - 'java.awt.image'
    - 'java.sql'
    - 'java.beans'
    - 'java.util.logging'
    - 'java.nio'
    - 'java.nio.channels'
  classes:
    - 'java.lang.Thread.UncaughtExceptionHandler'
    - 'java.util.Collection'
    - 'java.util.List'
    - 'java.util.ArrayList'
    - 'java.util.LinkedList'
    - 'java.util.Set'
    - 'java.util.HashSet'
    - 'java.util.TreeSet'
    - 'java.util.Map'
    - 'java.util.Map.Entry'
    - 'java.util.AbstractMap'
    - 'java.util.AbstractMap.SimpleImmutableEntry'
    - 'java.util.HashMap'
    - 'java.util.TreeMap'
    - 'java.util.LinkedHashMap'
    - 'java.util.Spliterators'
    - 'java.util.Spliterators.AbstractSpliterator'
    - 'java.nio.channels.FileChannel.MapMode'
    - 'org.jetbrains.annotations.Contract'
    - 'org.jetbrains.annotations.NotNull'
    - 'org.jetbrains.annotations.Nullable'
    - 'org.jetbrains.annotations.ApiStatus'
    - 'java.lang.annotation.ElementType'
    - 'java.lang.annotation.Retention'
    - 'java.lang.annotation.RetentionPolicy'
    - 'java.lang.annotation.Target'
    - 'lombok.AllArgsConstructor'
    - 'lombok.NoArgsConstructor'
    - 'lombok.RequiredArgsConstructor'
    - 'lombok.Getter'
    - 'lombok.Setter'
    - 'lombok.AccessLevel'
    - 'lombok.EqualsAndHashCode'
    - 'lombok.ToString'
    - 'lombok.Builder'
    - 'lombok.Data'

formats:
  module:
    docString: |
      """
      Python module generated from Java source file %class%
      
      Java source file obtained from artifact %group_id%:%artifact_id%:%artifact_version%
      
      Because this Python module is automatically generated, it may contain errors
      and/or code that cannot be parsed. Please report these issues at
      https://github.com/magicmq/docs-translator/issues
      """
    importDeclaration: 'from %package% import %module%'
  class_:
    declaration: 'class %name%:'
    declarationExtending: 'class %name%(%extends%):'
  enum:
    declaration: 'class %name%(Enum):'
    entryRegular: '%name% = %num%'
    entryWithArgs: '%name% = (%args%)'
  function:
    initDefinition: 'def __init__(%params%):'
    definition: 'def %name%(%params%) -> %returns%:'
    parameterRegular: '%name%: %type%'
    parameterVararg: '*%name%: Tuple[%type%, ...]'
    returnRegular: '...'
    returnWithValue: 'return %value%'
  field:
    initializer: '%name% = %value%'
  docString:
    author: 'Author(s): %text%'
    deprecated: ':deprecated: %text%'
    param: ':param %param%: %text%'
    typeParam: 'Type `%type%`: %text%'
    return: ':return: %text%'
    see: ':see: %text%'
    serial: 'Serial: %text%'
    serialData: 'Serial Data: %text%'
    serialField: 'Serial Field: %text%'
    since: 'Since: %text%'
    throw: ':raises %exception%: %text%'
    version: 'Version: %text'
    unknown: 'Unknown JavaDoc Tags:'
    unknownTag: '- %tag%: %text%'
  packaging:
    setup: |
      from setuptools import setup, find_namespace_packages
      
      setup(
          name='%name%',
          version='%version%',
          author='%author%',
          author_email='%author_email%',
          description='%description%',
          url='%url%',
          py_modules=[%py_modules%],
          packages=find_namespace_packages(),
          python_requires='%python_requires%',
          classifiers = [
              %classifiers%
          ],
      )
    pyProject: |
      [build-system]
      requires = [%requires%]
      build-backend = "%build_backend%"

packaging:
  setup:
    name: 'pyspigot-bukkit-sources'
    version: '0.8.0'
    author: 'magicmq'
    authorEmail: 'business@magicmq.dev'
    description: 'Translated PySpigot-Bukkit sources for writing PySpigot scripts'
    url: 'https://pyspigot-docs.magicmq.dev'
    pyModules:
      - 'https://raw.githubusercontent.com/magicmq/pyspigot/refs/tags/v0.8.0/bukkit/src/main/resources/Lib/pyspigot.py'
      - 'https://raw.githubusercontent.com/magicmq/pyspigot/refs/tags/v0.8.0/core/src/main/resources/Lib/function.py'
    pythonRequires: '>=3.6'
    classifiers:
      - 'Programming Language :: Python :: 3'
      - 'Natural Language :: English'
      - 'Topic :: Software Development :: Libraries :: Java Libraries'
      - 'License :: OSI Approved :: Apache Software License'
  pyProject:
    requires:
      - 'setuptools>=42'
      - 'wheel'
    buildBackend: 'setuptools.build_meta'
  manifest:
    - 'include LICENSE'
  license: 'https://www.apache.org/licenses/LICENSE-2.0.txt'